development:
  adapter: mysql2
  encoding: utf8
  database: reservation_service_development
  pool: 5
  username: root
  password: dummy
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: reservation_service_test
  pool: 5
  username: root
  password: dummy
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DB_NAME'] || 'reservation_service_production' %>
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
